CREATE TABLE "Users" ( 
    "Id" SERIAL PRIMARY KEY, 
    "Username" VARCHAR(255) NOT NULL, 
    "Email" VARCHAR(255) NOT NULL UNIQUE, 
    "PasswordHash" TEXT NOT NULL, 
    "Status" VARCHAR(50) NOT NULL DEFAULT 'Active',
    "CreatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, 
    "UpdatedAt" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP 
);